Fix psi.desktop file
error: value "SelectProfile" for string list key "Actions" in group
"Desktop Entry" does not have a semicolon (';') as trailing character